### ISSUE TITLE
开启调试进程后 无法命中断点

### ISSUE THREAD

**Issue by moyuanhua** [yuzukwok/eggjs-dev-tools#1]
使用的系统是windows10 + vscode 最新版本
代码是egg快速入门的教程
使用npm run dev 是可以正常访问的  
使用npm run dev -- --inspect 也能正常访问
在ctrl +1 之后开启调试进程 可是为什么不命中断点呢

**Comment by yuzukwok** [comment]
推荐使用这个插件，https://github.com/eggjs/egg-development-proxyworker

这样可以通过attach 固定端口，直接在vscode中调试，而不用在意调试端口的变化

**Comment by moyuanhua** [comment]
@yuzukwok 多谢提供资源
